loginScreen:
<loginScreen>:
    BoxLayout:
        orientation: 'vertical'
        spacing: dp(10)
        padding: dp(20)

        MDLabel:
            text: 'Inicio de Sesión'
            halign: 'center'
            theme_text_color: 'Custom'
            text_color: app.theme_cls.primary_color
            font_style: 'H5'
            size_hint_y: None
            height: self.texture_size[1]

        Image:
            source: 'foto_logo.png'  # Reemplaza con la ruta de tu imagen o logo
            size_hint: None, None
            size: dp(200), dp(200)
            halign: 'center'

        MDTextField:
            id: username
            hint_text: 'Usuario'
            mode: 'rectangle'
            pos_hint: {'center_x': 0.5}

        MDTextField:
            id: password
            hint_text: 'Contraseña'
            mode: 'rectangle'
            pos_hint: {'center_x': 0.5}
            password: True

        MDTextButton:
            text: 'He olvidado la contraseña'
            pos_hint: {'center_x': 0.5}
            custom_color: app.theme_cls.primary_color

        MDRaisedButton:
            text: 'Iniciar Sesión'
            pos_hint: {'center_x': 0.5}
            md_bg_color: app.theme_cls.accent_color
            on_release: app.login(username.text,password.text)